[package]
name = "lsp"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
air_r_parser.workspace = true
air_r_syntax.workspace = true
anyhow.workspace = true
biome_parser.workspace = true
crossbeam.workspace = true
futures.workspace = true
itertools.workspace = true
line-index.workspace = true
log.workspace = true
memchr.workspace = true
serde.workspace = true
serde_json.workspace = true
struct-field-names-as-array.workspace = true
text-size.workspace = true
tokio = { workspace = true, features = ["full"] }
tower-lsp.workspace = true
tracing.workspace = true
tree-sitter.workspace = true
triomphe.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["v4"] }

[lints]
workspace = true

[dev-dependencies]
assert_matches.workspace = true
bytes.workspace = true
futures-util.workspace = true
httparse.workspace = true
insta.workspace = true
lsp_test.workspace = true
memchr.workspace = true
tests_macros.workspace = true
tokio-util.workspace = true
