[package]
name = "lsp"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
crossbeam = "0.8.4"
futures = "0.3.31"
itertools = "0.13.0"
log = "0.4.22"
serde.workspace = true
serde_json = "1.0.132"
struct-field-names-as-array = "0.3.0"
tokio = { version = "1.41.1", features = ["full"] }
tower-lsp = "0.20.0"
tracing.workspace = true
tree-sitter = "0.23.0"
url = "2.5.3"
uuid = { version = "1.11.0", features = ["v4"] }

[lints]
workspace = true
